name: "Khulnasoft Gradle (jdk14)"
description: "Check your Gradle application for vulnerabilties using Khulnasoft"
author: "Md Sulaiman"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Khulnasoft command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Khulnasoft"
  json:
    description: "Output a khulnasoft.json file with results if running the test command"
    default: false
runs:
  using: "docker"
  image: "docker://khulnasoft/khulnasoft:gradle-jdk14"
  env:
    FORCE_COLOR: 2
    KHULNASOFT_INTEGRATION_NAME: GITHUB_ACTIONS
    KHULNASOFT_INTEGRATION_VERSION: gradle-jdk14
  args:
  - khulnasoft
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
