# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches:
      - 'main'

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: get_yamls
        run: |
          set -xv
          yamls=$(find . -name "*.y*ml" -not -path "*/.khulnasoft/source.yaml" -not -path "*/action.yaml" -exec echo {} +)
          echo "files=${yamls}" >> "$GITHUB_OUTPUT"
      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
