name: test-setup-registry

on: [pull_request]

jobs:
  test-mem:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - id: changed-registry
      uses: tj-actions/changed-files@c3a1bb2c992d77180ae65be6ae6c166cf40f857c # v45.0.3
      with:
        files: |
          ./setup-registry/**
          .github/workflows/test-setup-registry.yaml

    - if: steps.changed-registry.outputs.any_changed == 'true'
      uses: ./setup-registry
      with:
        port: 8081

    - if: steps.changed-registry.outputs.any_changed == 'true'
      run: |
        curl -v http://localhost:8081/v2/
        crane copy cgr.dev/chainguard/static:latest-glibc localhost:8081/static:test

  test-disk:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - id: changed-registry
      uses: tj-actions/changed-files@c3a1bb2c992d77180ae65be6ae6c166cf40f857c # v45.0.3
      with:
        files: |
          ./setup-registry/**
          .github/workflows/test-setup-registry.yaml

    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      if: steps.changed-registry.outputs.any_changed == 'true'

    - if: steps.changed-registry.outputs.any_changed == 'true'
      uses: ./setup-registry
      with:
        port: 8081
        disk: true

    - if: steps.changed-registry.outputs.any_changed == 'true'
      run: |
        curl -v http://localhost:8081/v2/
        crane copy cgr.dev/chainguard/static:latest-glibc localhost:8081/static:test
